#!/usr/bin/env bash
#
# Build the THIRD-PARTY-LICENSES/ tree for one RONDO release package.
#
# The canonical packager (`scripts/build_codex_package.py`) copies executables
# and nothing else -- it carries no license text at all. Everything a
# redistributable archive needs (Apache-2.0 section 4, the LGPL obligations of
# the bundled bubblewrap, and the permissive notices of the statically linked
# Cargo closure) therefore has to be assembled here.
#
# Coverage is deliberately two-layered, because one report cannot express both:
#   1. the Cargo dependency closure, generated from the committed Cargo.lock by
#      cargo-about, per shipped binary and per target; and
#   2. the native V8/ICU code inside the prebuilt librusty_v8 archive, which is
#      downloaded outside Cargo and is invisible to Cargo tooling.

set -euo pipefail

PRODUCT_DIR=""
TARGET=""
OUT_DIR=""
ENTRYPOINT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --product-dir) PRODUCT_DIR="$2"; shift 2 ;;
    --target)      TARGET="$2";      shift 2 ;;
    --out)         OUT_DIR="$2";     shift 2 ;;
    --entrypoint)  ENTRYPOINT="$2";  shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

: "${PRODUCT_DIR:?--product-dir is required (mydev|multidev)}"
: "${TARGET:?--target is required}"
: "${OUT_DIR:?--out is required}"
: "${ENTRYPOINT:?--entrypoint is required (rondo|rondo-multi)}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
LICENSE_SRC="${REPO_ROOT}/.github/licenses"
CODEX_RS="${REPO_ROOT}/${PRODUCT_DIR}/codex-rs"

# The `v8` submodule pinned by rusty_v8 v150.4.0, i.e. the exact V8 source the
# prebuilt archive was compiled from. Bump this together with the `v8` crate
# version and re-vendor the texts under .github/licenses/vendor/.
V8_REVISION="ac1e23989121713ca642f6650b34deff7b686896"

if [[ ! -d "$CODEX_RS" ]]; then
  echo "no such product workspace: $CODEX_RS" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

# --- 1. bubblewrap ----------------------------------------------------------
# bwrap is NOT a bundled external program: `codex-rs/bwrap/build.rs` compiles the
# vendored C sources into a Rust wrapper with cc::Build and renames `main` to
# `bwrap_main`. LICENSE in that directory is only a symlink to COPYING, so one
# copy is the complete text.
bwrap_copying="${CODEX_RS}/vendor/bubblewrap/COPYING"
if [[ ! -f "$bwrap_copying" ]]; then
  echo "missing bubblewrap COPYING at ${bwrap_copying}" >&2
  exit 1
fi
cp "$bwrap_copying" "${OUT_DIR}/bubblewrap-0.11.2-COPYING"

# --- 2. Prebuilt binaries fetched by the packager ---------------------------
# ripgrep and the patched zsh are downloaded through the DotSlash manifests in
# <product>/scripts/codex_package/. Their license texts are vendored under
# .github/licenses/vendor/ so a release never depends on a third-party host
# being reachable.
copy_vendored() {
  local f
  for f in "$@"; do
    if [[ ! -s "${LICENSE_SRC}/vendor/${f}" ]]; then
      echo "missing or empty vendored license text: ${LICENSE_SRC}/vendor/${f}" >&2
      exit 1
    fi
    cp "${LICENSE_SRC}/vendor/${f}" "${OUT_DIR}/${f}"
  done
}

copy_vendored ripgrep-15.2.0-LICENSE-MIT ripgrep-15.2.0-UNLICENSE zsh-77045ef8-LICENCE

# --- 3. Cargo dependency closure, per shipped binary ------------------------
# Generated against the committed lock file and filtered to the release target,
# so the report describes what is actually linked rather than every optional
# platform dependency in the graph.
if ! command -v cargo-about >/dev/null 2>&1; then
  echo "cargo-about is not installed; cannot produce the Cargo license closure" >&2
  exit 1
fi

# about.hbs deliberately contains no handlebars comments and uses triple braces
# throughout. Double braces HTML-escape, which turned `PROVIDED "AS IS"` into
# `PROVIDED &quot;AS IS&quot;` and corrupted every reproduced license; a notice
# file has to be verbatim, and the output is Markdown, not HTML. A `{{! .. }}`
# comment is no good either -- one that mentions `}}` terminates early and the
# rest leaks into the generated file.
emit_cargo_closure() {
  local crate_dir="$1" binary_name="$2"
  local manifest="${CODEX_RS}/${crate_dir}/Cargo.toml"
  local dest="${OUT_DIR}/rust-dependencies-${binary_name}.md"
  local body
  body="$(mktemp)"

  if [[ ! -f "$manifest" ]]; then
    echo "missing manifest ${manifest}" >&2
    exit 1
  fi

  cargo about generate \
    --config "${LICENSE_SRC}/about.toml" \
    --manifest-path "$manifest" \
    --target "$TARGET" \
    --locked \
    --output-file "$body" \
    "${LICENSE_SRC}/about.hbs"

  {
    echo "# Rust dependency licenses — \`${binary_name}\`"
    echo
    echo "Target: \`${TARGET}\`"
    echo
    echo "Generated by cargo-about from the committed \`Cargo.lock\`."
    echo
    echo "**Scope note:** produced from Cargo metadata only. It does *not* cover the"
    echo "native V8 / ICU code linked in from the prebuilt \`librusty_v8_*.a\` archive,"
    echo "which is downloaded outside Cargo and is opaque to Cargo tooling."
    echo "See \`v8-icu-NOTICE.md\` for that closure."
    echo
    cat "$body"
  } > "$dest"

  rm -f "$body"
  echo "wrote ${dest}"
}

emit_cargo_closure cli "$ENTRYPOINT"
emit_cargo_closure code-mode-host codex-code-mode-host
emit_cargo_closure bwrap bwrap

# --- 4. Native V8 / ICU closure ---------------------------------------------
# The prebuilt librusty_v8 archive is fetched outside Cargo, so cargo-about
# cannot see the V8 engine or the ICU data linked in through it. BSD-3-Clause
# and the Unicode license both require the notice to be reproduced *with the
# binary distribution*, so the texts travel in the package; a link would not
# discharge the obligation. The V8 texts are taken from the exact submodule
# revision that rusty_v8 v150.4.0 pins.
cp "${LICENSE_SRC}/v8-icu-NOTICE.md" "${OUT_DIR}/v8-icu-NOTICE.md"
copy_vendored \
  "v8-${V8_REVISION:0:12}-LICENSE" \
  "v8-${V8_REVISION:0:12}-LICENSE.fdlibm" \
  "v8-${V8_REVISION:0:12}-LICENSE.strongtalk" \
  "v8-${V8_REVISION:0:12}-LICENSE.v8" \
  rusty_v8-150.4.0-LICENSE \
  icu4c-LICENSE

# --- 5. Index ---------------------------------------------------------------
cat > "${OUT_DIR}/README.md" <<EOF
# Third-party licenses

Components redistributed inside this RONDO package, for target \`${TARGET}\`.

RONDO itself, and the upstream OpenAI Codex code it is derived from, are covered
by the \`LICENSE\` and \`NOTICE\` files at the root of this archive.

| Component | Version | Kind | License | Text |
|---|---|---|---|---|
| bubblewrap | 0.11.2 | C source compiled into the \`bwrap\` Rust wrapper | LGPL-2.0-or-later | \`bubblewrap-0.11.2-COPYING\` |
| ripgrep (\`codex-path/rg\`) | 15.2.0 | prebuilt binary | MIT or Unlicense | \`ripgrep-15.2.0-LICENSE-MIT\`, \`ripgrep-15.2.0-UNLICENSE\` |
| patched zsh (\`codex-resources/zsh/bin/zsh\`) | commit \`77045ef8\` + Codex patch | prebuilt binary | zsh license (MIT-like) | \`zsh-77045ef8-LICENCE\` |
| Cargo dependency closure | per \`Cargo.lock\` | statically linked | permissive; see reports | \`rust-dependencies-*.md\` |
| V8 engine | submodule \`${V8_REVISION:0:12}\` pinned by rusty_v8 150.4.0 | prebuilt static archive | BSD-3-Clause | \`v8-${V8_REVISION:0:12}-LICENSE\`, \`.fdlibm\`, \`.strongtalk\`, \`.v8\` |
| \`rusty_v8\` bindings | 150.4.0 | prebuilt static archive | MIT | \`rusty_v8-150.4.0-LICENSE\` |
| ICU locale data | via \`deno_core_icudata\` 0.77.0 | linked data | Unicode License V3 | \`icu4c-LICENSE\` |

The three rows above are **not** covered by the \`rust-dependencies-*.md\` reports;
see \`v8-icu-NOTICE.md\` for why Cargo tooling cannot see them.

## bubblewrap: corresponding source

bubblewrap is LGPL-2.0-or-later and is **not** shipped as a standalone external
program. \`${PRODUCT_DIR}/codex-rs/bwrap/build.rs\` compiles the vendored C sources
with \`cc::Build\`, renaming \`main\` to \`bwrap_main\` so the Rust wrapper in
\`bwrap/src/main.rs\` can call it.

The corresponding source for the exact \`bwrap\` in this package is the
\`${PRODUCT_DIR}/codex-rs/vendor/bubblewrap/\` directory of this release's git tag,
and the build entrypoint is \`${PRODUCT_DIR}/codex-rs/bwrap/build.rs\`.

## patched zsh: corresponding source

The bundled zsh is built from the zsh sources at commit
\`77045ef899e53b9598bebc5a41db93a548a40ca6\` (upstream:
\`https://git.code.sf.net/p/zsh/code\`) with the patch at
\`${PRODUCT_DIR}/codex-rs/shell-escalation/patches/zsh-exec-wrapper.patch\`
applied. The binary itself is downloaded from the upstream Codex releases via
the DotSlash manifest \`${PRODUCT_DIR}/scripts/codex_package/codex-zsh\`.
EOF

echo "third-party license tree written to ${OUT_DIR}"
ls -la "$OUT_DIR"
