mod backend;
mod client;
mod cloud_config;
mod cloud_scorer;
mod cloud_template;
#[cfg(test)]
mod config_tests;
mod contract;
mod failure;
mod identity;
mod packet;
mod real_scorer;
mod resource;
mod scorer;
mod service;
mod transport;
mod wire;

pub use client::ClientConfig;
pub use client::PublicationCriticClient;
pub use cloud_config::CLOUD_BACKEND_PROTOCOL;
pub use cloud_config::CloudScorerConfig;
pub use cloud_config::CloudScorerConfigError;
pub use cloud_config::CloudScorerDescriptor;
pub use cloud_config::cloud_reference_scoring_identity;
pub use cloud_config::provider_managed_model_identity;
pub use cloud_scorer::CloudPublicationScorer;
pub use contract::Verdict;
pub use failure::ContractFailure;
pub use failure::CriticFailure;
pub use failure::IdentityField;
pub use failure::InfrastructureFailure;
pub use failure::ScoreFailureKind;
pub use identity::ComponentIdentity;
pub use identity::FiniteValue;
pub use identity::IdentityComponent;
pub use identity::ModelIdentity;
pub use identity::PassRule;
pub use identity::ProtocolVersion;
pub use identity::QualificationIdentity;
pub use identity::ScoreDomain;
pub use identity::ScoringIdentity;
pub use identity::ServiceIdentity;
pub use identity::controlled_test_identity;
pub use packet::ActorRole;
pub use packet::CandidateEvidenceWindow;
pub use packet::ContextFreshness;
pub use packet::ContinuityContext;
pub use packet::ContinuityCoverage;
pub use packet::EvidenceV1;
pub use packet::FactReferenceCountCoverage;
pub use packet::FactReferenceSummary;
pub use packet::LocalScope;
pub use packet::MAX_HANDOFF_BYTES;
pub use packet::MAX_HANDOFF_SCALARS;
pub use packet::MAX_PRIOR_PUBLICATIONS;
pub use packet::MAX_SUMMARY_BYTES;
pub use packet::MAX_SUMMARY_SCALARS;
pub use packet::MAX_TITLE_BYTES;
pub use packet::MAX_TITLE_SCALARS;
pub use packet::MAX_VISIBLE_FACT_REFERENCES;
pub use packet::ObservationAvailability;
pub use packet::PriorEvidence;
pub use packet::PriorPublication;
pub use packet::PublicationCandidate;
pub use packet::PublicationPacket;
pub use packet::SemanticEntailmentPolicy;
pub use packet::TargetKind;
pub use real_scorer::RealPublicationScorer;
pub use real_scorer::RealScorerConfig;
pub use real_scorer::RealScorerConfigError;
pub use real_scorer::RealScorerDescriptor;
pub use real_scorer::RealScorerShutdownError;
pub use real_scorer::WORKER_PROTOCOL;
pub use resource::DEFAULT_CLIENT_TIMEOUT;
pub use resource::DEFAULT_FORCE_SHUTDOWN_TIMEOUT;
pub use resource::DEFAULT_GRACEFUL_SHUTDOWN_TIMEOUT;
pub use resource::DEFAULT_IO_TIMEOUT;
pub use resource::DEFAULT_JOB_TIMEOUT;
pub use resource::DEFAULT_MAX_CONCURRENCY;
pub use resource::DEFAULT_QUEUE_CAPACITY;
pub use resource::DEFAULT_REQUEST_BYTES;
pub use resource::DEFAULT_RESPONSE_BYTES;
pub use resource::DEFAULT_STARTUP_TIMEOUT;
pub use resource::MIN_PROTOCOL_FRAME_BYTES;
pub use resource::RuntimeLimits;
pub use resource::ServiceConfig;
pub use resource::ServiceDescriptor;
pub use resource::controlled_test_descriptor;
pub use resource::validate_expected_descriptor;
pub use scorer::PublicationScorer;
pub use scorer::RawScorerOutput;
pub use scorer::ScorerError;
pub use scorer::ScorerStatus;
pub use service::ServiceRunError;
pub use service::serve;
pub use wire::ServicePhase;
pub use wire::ServiceStatus;
pub use wire::StartupAnnouncement;
