// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionFactProvenance } from "./DurableSessionFactProvenance";
import type { DurableSessionOperationAvailability } from "./DurableSessionOperationAvailability";

/**
 * One operation's availability and the fact source supporting it.
 */
export type DurableSessionOperation = { availability: DurableSessionOperationAvailability, provenance: DurableSessionFactProvenance, };
