// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionOperation } from "./DurableSessionOperation";

/**
 * Availability of the Session operations that a query may present.
 */
export type DurableSessionOperations = { resume: DurableSessionOperation, setRootState: DurableSessionOperation, close: DurableSessionOperation, archive: DurableSessionOperation, unarchive: DurableSessionOperation, delete: DurableSessionOperation, };
