// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical or observation source for one projected fact axis.
 */
export type DurableSessionFactProvenance = "sessionMeta" | "threadStore" | "committedTeamSnapshot" | "serverRuntimeObservation" | "derivedPolicy" | "unavailable";
