// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionView } from "./DurableSessionView";

/**
 * Response for reading one canonical durable Session.
 */
export type DurableSessionReadResponse = { session: DurableSessionView, };
