// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for discovering canonical durable Sessions.
 */
export type DurableSessionListParams = {
/**
 * Opaque pagination cursor returned by a previous call for the same source.
 */
cursor?: string | null,
/**
 * Optional page size; the server applies a bounded default and maximum.
 */
limit?: number | null,
/**
 * Selects the archived source when true and the active source when false.
 */
archived?: boolean, };
