// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Domain lifecycle, independent of storage placement and runtime residency.
 */
export type DurableSessionDomainLifecycle = "open" | "closing" | "closed" | "failed" | "unknown";
