// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionTeamProducerState } from "./DurableSessionTeamProducerState";
import type { DurableSessionTeamRootState } from "./DurableSessionTeamRootState";

/**
 * One committed Team version within an event projection.
 */
export type DurableSessionTeamVersionProjection = { versionId: string, authorThreadId: string, authorLabel: string, summary: string, producerState: DurableSessionTeamProducerState, rootState: DurableSessionTeamRootState, retired: boolean, };
