// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an operation is unknown or unavailable in this projection.
 */
export type DurableSessionOperationAvailabilityReason = "readIncomplete" | "identityUnavailable" | "storageUnavailable" | "lifecycleUnknown" | "residencyUnknown" | "ownerUnavailableHere" | "notObservedHere" | "alreadyArchived" | "notArchived" | "closing" | "closed" | "failed" | "childSession" | "unsupported";
