// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionFactProvenance } from "./DurableSessionFactProvenance";

/**
 * Provenance for each independent Session fact axis.
 */
export type DurableSessionProvenance = { identity: DurableSessionFactProvenance, storageStatus: DurableSessionFactProvenance, domainLifecycle: DurableSessionFactProvenance, residency: DurableSessionFactProvenance, team: DurableSessionFactProvenance, };
