// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical durable Session identity and its Root lineage identity.
 */
export type DurableSessionIdentity = { sessionId: string,
/**
 * `None` means that a canonical Root identity could not be established.
 */
rootThreadId: string | null, };
