// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionTeamRole } from "./DurableSessionTeamRole";

/**
 * One participant included in the bounded committed Team projection.
 */
export type DurableSessionTeamParticipantProjection = { threadId: string, role: DurableSessionTeamRole, label: string, };
