// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Field-free operation identity used in outcomes after the request payload is consumed.
 */
export type DurableSessionControlOperationKind = "setRootState" | "close" | "archive" | "unarchive" | "delete";
