// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionOperationAvailabilityReason } from "./DurableSessionOperationAvailabilityReason";

/**
 * Whether an operation is available from the currently proven facts.
 */
export type DurableSessionOperationAvailability = { "status": "available" } | { "status": "unknown", reason: DurableSessionOperationAvailabilityReason, } | { "status": "unavailable", reason: DurableSessionOperationAvailabilityReason, };
