// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed, side-effect-free reason why a control attempt was rejected.
 */
export type DurableSessionControlRejectionReason = "stalePrecondition" | "wrongStorage" | "ownerUnavailable" | "notCurrentOwner" | "activeWriter" | "conflict" | "notFound" | "unsupported" | "invalidState";
