// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionTeamVersionProjection } from "./DurableSessionTeamVersionProjection";

/**
 * One bounded event from the committed Team snapshot.
 */
export type DurableSessionTeamEventProjection = { eventId: string, title: string, versions: Array<DurableSessionTeamVersionProjection>, omittedVersions: number, };
