// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persistent source selected for this Session record.
 */
export type DurableSessionStorageStatus = "active" | "archived" | "unknown";
