// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionControlEffect } from "./DurableSessionControlEffect";
import type { DurableSessionControlOperationKind } from "./DurableSessionControlOperationKind";
import type { DurableSessionControlRejectionReason } from "./DurableSessionControlRejectionReason";

/**
 * Certainty-preserving outcome returned by the control boundary.
 */
export type DurableSessionControlOutcome = { "type": "applied", effect: DurableSessionControlEffect, } | { "type": "rejected", operation: DurableSessionControlOperationKind, reason: DurableSessionControlRejectionReason, message: string, } | { "type": "partial", operation: DurableSessionControlOperationKind, completedThreadIds: Array<string>, message: string, } | { "type": "unknown", operation: DurableSessionControlOperationKind, message: string, };
