// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionListIncompleteReason } from "./DurableSessionListIncompleteReason";
import type { DurableSessionView } from "./DurableSessionView";

/**
 * One bounded page of canonical durable Sessions.
 */
export type DurableSessionListResponse = { data: Array<DurableSessionView>, nextCursor: string | null,
/**
 * Whether discovery completed against the selected source for this request.
 * This is independent of whether `next_cursor` offers another complete page.
 */
complete: boolean, incompleteReason: DurableSessionListIncompleteReason | null, };
