// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionResidency } from "./DurableSessionResidency";
import type { DurableSessionStorageStatus } from "./DurableSessionStorageStatus";

/**
 * Query proof that the server must revalidate before applying a control operation.
 */
export type DurableSessionControlPrecondition = { expectedStorageStatus: DurableSessionStorageStatus, expectedResidency: DurableSessionResidency, teamInstanceId: string, teamRevision: number, commitGeneration: number, commitFingerprint: string, };
