// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for reading one canonical durable Session.
 */
export type DurableSessionReadParams = {
/**
 * Canonical Session identity to cross-check against the durable marker.
 */
sessionId: string,
/**
 * Canonical Root identity used only to locate the durable record. The
 * server must still cross-check it against the marker and Session identity.
 */
rootThreadId: string, };
