// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionTeamRole } from "./DurableSessionTeamRole";

/**
 * Session member through whose lineage the Team projection is viewed.
 */
export type DurableSessionTeamViewer = { threadId: string, role: DurableSessionTeamRole, };
