// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionControlPrecondition } from "./DurableSessionControlPrecondition";
import type { DurableSessionDomainLifecycle } from "./DurableSessionDomainLifecycle";
import type { DurableSessionIdentity } from "./DurableSessionIdentity";
import type { DurableSessionOperations } from "./DurableSessionOperations";
import type { DurableSessionProvenance } from "./DurableSessionProvenance";
import type { DurableSessionReadStatus } from "./DurableSessionReadStatus";
import type { DurableSessionResidency } from "./DurableSessionResidency";
import type { DurableSessionStorageStatus } from "./DurableSessionStorageStatus";
import type { DurableSessionTeamProjection } from "./DurableSessionTeamProjection";

/**
 * Read-only projection of one canonical durable Session.
 *
 * Durable identity, storage placement, domain lifecycle, server-local runtime
 * residency, operation availability, and read completeness remain independent
 * axes. A caller must not infer one axis from another.
 */
export type DurableSessionView = { identity: DurableSessionIdentity, storageStatus: DurableSessionStorageStatus, domainLifecycle: DurableSessionDomainLifecycle, residency: DurableSessionResidency, operationAvailability: DurableSessionOperations,
/**
 * Exact query proof accepted by `session/control`, when the read can prove
 * every required identity, storage, residency, and committed Team fact.
 */
controlPrecondition: DurableSessionControlPrecondition | null, provenance: DurableSessionProvenance, readStatus: DurableSessionReadStatus,
/**
 * Present only when one complete committed Team snapshot was projected.
 */
team: DurableSessionTeamProjection | null, };
