// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionTeamEventProjection } from "./DurableSessionTeamEventProjection";
import type { DurableSessionTeamParticipantProjection } from "./DurableSessionTeamParticipantProjection";
import type { DurableSessionTeamViewer } from "./DurableSessionTeamViewer";

/**
 * Bounded projection of one complete committed Team snapshot.
 */
export type DurableSessionTeamProjection = { teamInstanceId: string,
/**
 * Canonical durable commit generation for this exact snapshot.
 */
commitGeneration: number,
/**
 * SHA-256 of the complete validated snapshot payload, encoded as
 * `sha256:` followed by 64 lowercase hexadecimal digits. This includes
 * state omitted from the bounded projection.
 */
commitFingerprint: string,
/**
 * Team domain revision stored in this exact snapshot.
 */
revision: number, viewer: DurableSessionTeamViewer, participants: Array<DurableSessionTeamParticipantProjection>, omittedParticipants: number, events: Array<DurableSessionTeamEventProjection>, omittedEvents: number, };
