// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confirmed domain effect of an applied control operation.
 */
export type DurableSessionControlEffect = { "type": "rootStateUpdated", changed: boolean, mutationRevision: number, } | { "type": "ownerClosed" } | { "type": "archived", affectedThreadIds: Array<string>, } | { "type": "unarchived" } | { "type": "deleted", affectedThreadIds: Array<string>, };
