// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionReadIssue } from "./DurableSessionReadIssue";

/**
 * Completeness of the durable read used to build this projection.
 */
export type DurableSessionReadStatus = { "status": "available" } | { "status": "incomplete", issue: DurableSessionReadIssue, } | { "status": "unavailable", issue: DurableSessionReadIssue, } | { "status": "unsupported", issue: DurableSessionReadIssue, };
