// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionTeamProducerState } from "./DurableSessionTeamProducerState";
import type { DurableSessionTeamRootState } from "./DurableSessionTeamRootState";

/**
 * Mutation requested from the current canonical Durable Session authority.
 */
export type DurableSessionControlOperation = { "type": "setRootState", versionId: string, expectedProducerState: DurableSessionTeamProducerState, expectedRootState: DurableSessionTeamRootState, nextRootState: DurableSessionTeamRootState, } | { "type": "close" } | { "type": "archive" } | { "type": "unarchive" } | { "type": "delete" };
