// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a list page cannot claim a complete read of its selected source.
 */
export type DurableSessionListIncompleteReason = "sourceUnavailable" | "sourceUnsupported" | "sourceChanged" | "budgetExhausted" | "recordUnreadable" | "recordIncompatible" | "classificationFailed" | "unknown";
