// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime residency observed only by the app-server answering this query.
 */
export type DurableSessionResidency = "observedOwnerHere" | "ownerUnavailableHere" | "notObservedHere" | "unknown";
