// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurableSessionControlOperation } from "./DurableSessionControlOperation";
import type { DurableSessionControlPrecondition } from "./DurableSessionControlPrecondition";

/**
 * Parameters for one authoritative Durable Session control attempt.
 */
export type DurableSessionControlParams = { sessionId: string, rootThreadId: string, precondition: DurableSessionControlPrecondition, operation: DurableSessionControlOperation, };
