// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed issue that limits or prevents a durable Session read.
 */
export type DurableSessionReadIssue = "sessionNotFound" | "sourceUnavailable" | "sourceUnsupported" | "sourceChanged" | "budgetExhausted" | "identityUnavailable" | "notCanonicalRoot" | "sessionRootIdentityMismatch" | "sessionMetaUnreadable" | "sessionMetaIncompatible" | "durableMarkerMissing" | "durableMarkerIncompatible" | "durableMarkerIdentityMismatch" | "teamSnapshotMissing" | "teamSnapshotCorrupt" | "teamSnapshotIncompatible" | "teamSnapshotValidationFailed" | "legacySession" | "durableSessionsDisabled" | "unknown";
