// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Caller-prepared local linked worktree to bind as a writer's primary workspace.
 */
export type WriterWorkspaceBindingParams = { worktreeRoot: AbsolutePathBuf, environmentId?: string | null, };
