// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { WriterWorkspaceBindingAvailability } from "./WriterWorkspaceBindingAvailability";

export type WriterWorkspaceBinding = { generation: number, worktreeRoot: AbsolutePathBuf, gitDir: AbsolutePathBuf, commonDir: AbsolutePathBuf, repositoryRoot: AbsolutePathBuf, environmentId: string, availability: WriterWorkspaceBindingAvailability, };
